spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:neurotech_desafio}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Show SQL
spring.jpa.show-sql=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

springdoc.swagger-ui.displayRequestDuration=true

