spring.application.name=neurotech_desafio
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}